# Travis example for Identifier created by Rafael Garibotti

sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - valgrind
      - cppcheck
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - echo "abc\n" > input.txt
  - echo "a\n" >> input.txt
  - echo "b\n" >> input.txt
  - echo "c\n" >> input.txt
  - cat input.txt
  - make cppcheck
  - make ARGS=input.txt valgrind
  - cat out.txt
  - make ARGS=input.txt sanitizers
  - cat out.txt
  #- make test
