# Travis example for Identifier created by Rafael Garibotti

sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - valgrind
      - cppcheck
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - make cppcheck
  - make valgrind
  - make sanitizers
  #- make test
